name: CI
run-name: CI Build
on: [ push ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          docker build -t ghcr.io/browsers-software/demo:latest < Dockerfile
          docker push ghcr.io/browsers-software/demo:latest
