name: CI
run-name: CI Build
on: [ push ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          docker build -t ghcr.io/Browsers-software/demo:latest https://github.com/docker/rootfs.git#container:docker
          docker push ghcr.io/Browsers-software/demo:latest
